const END_OF_DAY_HOUR: number = 17;
const START_OF_DAY_HOUR: number = 9;
const DEFAULT_TIME_INTERVAL_IN_HOURS: number = 4;
const DEFAULT_TIME_SPOT_SPAN_IN_MINS: number = 30;
const DEFAULT_TIME_ZONE: string = 'America/Guatemala';
const GOOGLE_CAL_DEFAULT_ATTENDEE_EMAIL: string = 'renatoperezc@gmail.com';

export {
  START_OF_DAY_HOUR,
  END_OF_DAY_HOUR,
  DEFAULT_TIME_INTERVAL_IN_HOURS,
  DEFAULT_TIME_SPOT_SPAN_IN_MINS,
  DEFAULT_TIME_ZONE,
  GOOGLE_CAL_DEFAULT_ATTENDEE_EMAIL
};
